import type { Customer } from "../type/other";
export const customerData: Customer[] = [
    {
        id: "#5089",
        customer: "Joseph Wheeler",
        date: "6 April, 2023",
        total: 2564,
        method: "CC",
        status: "Pending",
    },
    {
        id: "#5090",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Cancelled",
    },
    {
        id: "#5091",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Completed",
    },
    {
        id: "#5092",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Completed",
    },
    {
        id: "#5093",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Completed",
    },
    {
        id: "#5094",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Completed",
    },
    {
        id: "#5095",
        customer: "Jane Doe",
        date: "7 April, 2023",
        total: 1500,
        method: "Cash",
        status: "Completed",
    },
];
